### ISSUE TITLE
appimaged: Some of the AppImages are now lacking names in the menu

### ISSUE THREAD

**Issue by probonopd** [probonopd/go-appimage#123]
Have the suspiciion that f4ff888 was the last one working properly

@CalebQ42 did you have a chance to test `appimaged` with your changes on a sufficiently large set of AppImages?

**Comment by CalebQ42** [comment]
I did test several AppImage's, but I probably should have done a bit more testing, sorry.

The problem is probably that the AppImage's desktop file doesn't have a name. It's either that or the ini library being used is just having more issues with desktop files then I previously thought.

What AppImage is having this issue?

**Comment by CalebQ42** [comment]
@probonopd I made a quick fix that basically should make sure that a desktop file has a name. I also fixed an issue I found with how I had `appimaged` get thumbnails, sometimes resulting in the desktop entry just having no icon at all. These changes are currently on my fork, but I'd like to test the AppImage(s) you're having problems with to make sure it's not some entirely different problem before submitting a PR.

**Comment by probonopd** [comment]
Hello @CalebQ42 thanks for looking into this.

Has something changed regarding how desktop files are parsed? It seems that AppImages that do not pass `desktop-file-validate` get no name at all in the menu. 

The Ultimaker Cura AppImages seem to be affected, for example.

https://user-images.githubusercontent.com/2480569/104805711-055e2b80-57ca-11eb-9bad-ce44cc6357dc.mp4

**Comment by CalebQ42** [comment]
@probonopd It seems that the problem might have something to do with my squashfs library. For some reason it can't read ANYTHING from the cura's squashfs, but instead of just failing, it reads nothing and says everything is okay. Basically that means that when reading the desktop file, it _thinks_ it read it properly and doesn't populate the name.

As a consolation to myself, it seems something might be a _bit_ weird about it's squashfs because file-roller also doesn't like it. You can't view files before they're extracted (it says there's an error) and though it extracts it correctly, it says there was an error afterwards. Overall, very strange.

**Comment by CalebQ42** [comment]
Got it! I had used the wrong types (uint32 instead of uint64) when trying to read extended file inodes so I wasn't getting the right values on where the data was. This is the first squashfs image I've found that uses that particular type of inode so I hadn't yet run into this problem.

![Screenshot from 2021-01-16 03-31-15](https://user-images.githubusercontent.com/8998514/104808368-53b00200-57ab-11eb-8853-3dd9ee19bd25.png)
