### ISSUE TITLE
How to properly get rid of appimagelauncher

### ISSUE THREAD

**Issue by pepa65** [probonopd/go-appimage#126]
I thought I had uninstalled it, but `appimaged` is saying appimagelauncher's daemon is still ruinning. I don't see anything under `systemctl status` nor under `ps aux`. How/what does appimaged detect??

**Comment by probonopd** [comment]
> How/what does appimaged detect??

https://github.com/probonopd/go-appimage/blob/92b4e776ef5269211cd5104ce89c3b69507ff67b/src/appimaged/prerequisites.go#L75-L77

**Comment by probonopd** [comment]
Do you still have `~/.config/systemd/user/default.target.wants/appimagelauncherd.service`?

**Comment by pepa65** [comment]
Yes I did, wasn't aware of that location yet. Clearing it didn't help for starting, cleaned some other appimage stuff in HOME -- what an enormous mess! But still the same message. I'll reboot and see again.

**Comment by probonopd** [comment]
In case of further questions, please ask over at https://github.com/TheAssassin/AppImageLauncher how to remove all traces of it completely.

**Comment by pepa65** [comment]
Thanks, I appreciate your help.

**Comment by flyingicedragon** [comment]
> Do you still have `~/.config/systemd/user/default.target.wants/appimagelauncherd.service`?

Deleting this and run `systemctl --user daemon-reload` solved it for me. Thanks!

**Comment by Neko-Box-Coder** [comment]
Hi, this issue happened to me as well and had to do some googling to figure out what is happening despite removing AppImageLauncher.

I was confused since systemd didn't show up any appimagelauncher service as well.
I think it would be nice to add a suggestion for checking `~/.config/systemd/user/default.target.wants/appimagelauncherd.service` in the error desktop notification.
