### ISSUE TITLE
appimaged: configuration option to specify application search folders

### ISSUE THREAD

**Issue by psuter80** [probonopd/go-appimage#131]
I read read @probonopd comment https://github.com/probonopd/go-appimage/issues/101#issuecomment-732368132 regarding configurabiltiy and yet i am asking for configurability because I don't agree completely. Yes, it adds complexity, but only if an application does not come with defaults that work. 

as there are many issues here of people either requesting more directories to be monitored or to exclude driectories such as the Downloads directory (which is what i'm after too), I wold propose to introduce an optional environment variable like "APPIMAGE_PATH" or something like that, which is formatted like "PATH" and if set, replaces the hardcoded 'candidateDirectories in appimaged.go. 

Like this the app would still work as it does today, but it would give us an option to choose our own set of paths where we want to keep our appimages. 

To configure our own list of paths, we would then do it via systemd edit: 
```
  systemctl --user edit appimaged.service
```
and then add our environment variable: 
```
[Service]
Environment="APPIMAGE_PATH=~/Applications"
```
In the same way, more configuration options could be added in the future if necessary, always keeping the app in tact without any added complexity for users who like to run it with default settings. 

cheers
Pascal

**Comment by machitgarha** [comment]
I don't really know how the new appimaged implementation is different from the previous one, but the previous one was really IO-intensive, just because my `~/Downloads` directory was (and is) so huge. When I'm pretty sure that all my AppImages lives in `~/Downloads/apps` directory, then why should I wait for Firefox to load for a long time just after login on my HDD box, clearly because appimaged keeps searching for some AppImages in a wrong huge-size place?

Perhaps the new implementation is better and less resource-intensive, great, but I think it is not enough. A really better option would be adding this feature.

**Comment by probonopd** [comment]
Let's not work around symptoms by adding configuration options. If performance is not ok, then let's fix performance...

**Comment by machitgarha** [comment]
The problem is, the solution to fix the performance regression is, IMHO, to prevent iteration over non-sense directories, possibly huge in size. The best solution here is to give the user an option, and I don't understand why user should be restricted to the options that is considered by-design.

Well, I'm not really familiar with the implementation, nor with the Go language itself, however, another option would be restricting choices only to those having ".AppImage" file extension. Although it might be beneficial, I personally am interested in having such a config option.

**Comment by probonopd** [comment]
> The best solution here is to give the user an option

Options are usually in applications because the developers were too lazy to think through something and make it "just work". As a result, the user has to think about thing the developer should have thought about.

AppImages should "just work" without the user thinking anything.

**Comment by machitgarha** [comment]
> Options are usually in applications because the developers were too lazy to think through something and make it "just work". As a result, the user has to think about thing the developer should have thought about.

Not usually, sometimes. Making something just work is not the opposite of giving options to users. Some options are even mandatory.

The problem is not with preventing from the application to just work, but simply allowing users to change defaults. Many users might keep the defaults, that's OK. However, it should be notified that these directories are being scanned for AppImages, so somebody like me does not search for slow the reason of 1-minute-taking Firefox launch, and letting him to change them.

> AppImages should "just work" without the user thinking anything.

No doubt that AppImages just work, they are great. But, if you (we?) really have that in mind, one could say a GUI is a better option and in higher priority than anything else for the ease of use. Right?

**Comment by psuter80** [comment]
@probonopd I understand your philosophy, allthough I don't agree with it ;) .. but this is your project, your effort and your decision and i respect that. For that reason I'm closing this issue now, as this feature request clearly does not fit within the strategy behind go-appimage. thank's for your response.

**Comment by Korne127** [comment]
I think an option, e.g. by setting a configuration file somewhere, is really valuable.

It doesn't mean that the application author hasn't thought something through, but that some things are supposed to be tailored by the user to their specific needs. Imagine your IDE would force a specific code style because it doesn't want to give the users an option.

The most convincing argument imo is that a user has a specific directory structure in which they want to place their AppImages in. In this case they cannot use ``appimaged`` despite it being the perfect helper in that case.
And if someone not wants to scan for specific directories, then that's not work given to the user, but an understandable preference that the user should be able to express.

Of course, it should just work without the user having to set many options, but this could also be easily done by a default file (which equals the current one), which allows users to customise the list (which many people would appreciate and improve this project, and others can just ignore and use like now).

**Comment by HernandoR** [comment]
Just out of curiosity, would an AppImage work in ~/Download without `appimaged` watching it?

In my use case, ~/Downloads is just a pile of files that I downloaded from the internet, which may be broken, dangerous or useless. I would like to only integrate those I tested and would like to maintain, which are proved by moving into ~/Applications or other paths.

**Comment by Korne127** [comment]
Well, AppImages work everywhere, no matter whether it's watched by the daemon or not. It just automatically marks it as executable (so you don't have to) and integrates them into the desktop (e.g. app menus).

**Comment by probonopd** [comment]
I think the proper solution is to support AppImages directly in the file manager, so that they work without any additional daemons and workarounds. (Oh well, the format exists for decades now, and support is still... lacking.)
