### ISSUE TITLE
Allow building appimages on system with libnvidia* libraries

### ISSUE THREAD

**Issue by sjdrc** [probonopd/go-appimage#136]
Hi there,

I'm building on the Nvidia Jetson Nano platform. Using the continuous release images I get an error saying:
```
System (most likely libGL) uses libnvidia*, please build on another system that does not use NVIDIA drivers, exiting
```

After doing a custom build removing the call to `handleNvidia()`, I get a working appimage. It seems that this works due to the aarch64 platform doing things differently to x86_64 with Nvidia drivers. Would it be possible for you to add a flag in to bypass the nvidia driver check, or don't do this check on aarch64?

**Comment by probonopd** [comment]
Hi  @sjdrc 

If you ever want your AppImages to run not just on NVIDIA Jetson but also on other ARM devices, the you should better not try to bundle any NVIDIA specific libraries inside the AppImage.

If you are really sure that your AppImage shall never run anywhere else but on NVIDIA Jetson target systems, then you can try to comment out the `os.Exit(1)` here:

https://github.com/probonopd/go-appimage/blob/23ad67c727fb762867fe96db06d600a7cdaf297d/src/appimagetool/appdirtool.go#L637

I am not interesting to remove the check for the official version though, because I don't want to encourage people to build AppImages that run only on NVIDIA systems.

**Comment by sjdrc** [comment]
No worries, understand your reasons. We're using AppImages to deploy our application in house on custom devices, so we'll maintain a custom build then. Thanks for your help.

**Comment by probonopd** [comment]
Thanks for your understanding. Actually I am [considering to use NVIDIA Jetson for another project of mine](https://github.com/helloSystem/hello/issues/80), would you say the Jetson Nano is more capable as a general desktop machine (incuding watching YouTube video in the browser fullscreen) compared to the Raspberry Pi 4?

**Comment by sjdrc** [comment]
We use the devices headless to pull images off devices and encode video, so I couldn't speak to the desktop performance, but the GPU is far more capable than that of a Raspberry Pi. I wouldn't imagine there would be any problems using a lightweight WM at 1080p.

**Comment by probonopd** [comment]
> encode video

Yes, I imagine one could even do light video editing on those devices using Shotcut or similar software that supports NVENC...
