### ISSUE TITLE
Directories are not scanned recursively

### ISSUE THREAD

**Issue by machitgarha** [probonopd/go-appimage#140]
Personally, I have my AppImages inside `~/Downloads/apps` directory. When I move one of the AppImages into `~/Downloads`, it is detected. However, after waiting for a while, my AppImages in the mentioned directory are seemed to be ignored.

**Comment by probonopd** [comment]
This is for performance reasons.

The whole concept of desktop files sucks. 
Which is why I have shifted focus to [implementing AppDirs in the file manager "properly"](https://github.com/helloSystem/Filer/) these days.
In the same way, someone could implement native handling of AppImages in the file manager.
