### ISSUE TITLE
Currently, there is no way to configure watched directories

### ISSUE THREAD

**Issue by lukebemish** [probonopd/go-appimage#232]
Having used this for a little bit, I've noticed two fairly annoying limitations/issues:

First, even if directories other than `~/Applications` are being used to store AppImages instead, that directory gets created each time the service is restarted. This is rather annoying

Second, there's no way to specify which directories should be watched for AppImages. I would like to use a different directory (`.opt`, for example) to store appimages, but if I do so appimaged won't be able to find them. Some sort of configuration system with a way to specify directories (or exclude them; I don't actually want stuff in Downloads being integrated with my desktop, thank you very much) would solve this. I could look at writing and PRing something, but I'm not sure I am familiar enough with go to do this justice, so I'll see.

**Comment by probonopd** [comment]
Works as designed.

**Comment by brlin-tw** [comment]
Hello, I would like to also request this feature as I use ~/應用軟體 as the folder to put my Appimage and non-Appimage applications, which is the Taiwanese Chinese localized form of ~/Application.

Please consider extending the [xdg-user-dirs](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/) infrastructure to locate the actual path of the Applications folder from ~/.config/user-dirs.dirs, this allows localization and customization in a degree.

Thank you.

**Comment by RedSnt** [comment]
I can't symlink my way out of not having appimaged watching ~/Downloads, which is a bit annoying. It's the most unorganized folder after all, so appimaged ends up listing multiple shortcuts in the application launcher due to multiple versions of the same app.  

<details>
<summary>I failed create an apparmor profile that would deny access to ~/Downloads.</summary>
I'm not experienced enough to make an apparmor profile for a service apparently, but I did fix an auditd.pid issue on the journey, so not an entirely fruitless endeavour. 
</details>
