### ISSUE TITLE
Build for i686 Arch

### ISSUE THREAD

**Issue by Bhupesh-V** [probonopd/go-appimage#43]
Ended up here from [Bundling-Python-apps](https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps). Just realised that only amd64 builds are available on Releases page
Does go-appimage supports 32 bit Arch ?

https://github.com/probonopd/go-appimage/blob/1375a6de50bcbbcbdaa2d8b76a580c66f6bf68e4/.travis.yml#L4-L6

Should I create PR adding that ?

**Comment by probonopd** [comment]
Hi @Bhupesh-V. Go is great because it can build for all sorts of architectures, but appimagetool also needs some external (C/C++) command line tools to work, so we would need 32-bit versions of those as well.

I am already now having some trouble to get the external (C/C++) command line tools to compile: https://github.com/probonopd/static-tools

I would appreciate pull requests that would allow for this.

**Comment by Bhupesh-V** [comment]
So I tried building it locally but it raises the following error

```bash
appimagetool unsupported custom build

2020/07/01 20:16:38 Required helper tool uploadtool missing
```
I looked and it indeed has some todo left
https://github.com/probonopd/go-appimage/blob/1375a6de50bcbbcbdaa2d8b76a580c66f6bf68e4/src/appimagetool/appimagetool.go#L107-L108

Will you be willing to explain the process a little bit (or maybe point me to appropriate resources). I would be happy to contribute something here

**Comment by probonopd** [comment]
Hello @Bhupesh-V. The appimagetool implementation in this repository uses external tools (scripts and binaries) for many tasks, one of them is the `uploadtool` you mention.

When the AppImage of appimagetool is produced, it __should__ be downloaded and put into the AppImage here:

https://github.com/probonopd/go-appimage/blob/196ec2587d0d9954e113a52b85360d2643388bff/scripts/build.sh#L111

The real issue, however, is that the tools at https://github.com/probonopd/static-tools/releases/tag/continuous are currently only there for x86_64 because I did not succeed yet in building them for the other architectures. Any help there would be appreciated.

> Although I had success by following this wiki and I used AppImageKit's i686 releases.

That wiki describes the "old" way of doing things, not taking into account this (still very new) Go-based tool.

**Comment by probonopd** [comment]
I now succeeded building https://github.com/probonopd/static-tools/releases/tag/continuous for other architectures, so we can pick this up again.

**Comment by probonopd** [comment]
Is available now.
